menu:
	Home: /
	Archives: /archives

ext_link:
	

blogroll:
	Leigh: http://zhuli.me


widgets: 
- category
- tagcloud
- blogroll

excerpt_link: Read More

twitter:
	username:
	show_replies: false
	tweet_count: 5

bdlike:
	enable: true
	type: large
	uid: 
	color: blue
	share: yes

fancybox: true

google_analytics:
rss:

social_comment:
	plat: 1
	duoshuo_shortname: 
	disqus_shortname: 