menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

# Social comment platform
## @plat: 
##      1 for disqus
##      2 for duoshuo
social_comment:
  plat: 2
  disqus_shortname: 
  duoshuo_shortname: 