menu:
  Home: /
  Archives: /archives

ext_link:
  

blogroll:
  Leigh: http://zhuli.me
  Zoe: http://zoechan.me
  Test: http://test


widgets: 
- category
- tagcloud
- blogroll

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: true

fancybox: true

google_analytics:
rss:

social_comment:
  plat: 2
  duoshuo_shortname: zhulime
  disqus_shortname: lisposter