menu:
	Home: /
	About: /about
	Archive: /archives

ext_link:
	twitter:  
	github:  
	rss:  

blogroll:
	Leigh: http://zhuli.me


widgets: 
- blogroll

excerpt_link: Read More

twitter:
	username:
	show_replies: false
	tweet_count: 5

bdlike:
	enable: true
	type: large
	uid: 
	color: blue
	share: yes

fancybox: true

# baidu_tongji: this is your baidu tongji specific code.
# Get your js code from http://tongji.baidu.com, it will contain a string like: hm.baidu.com/h.js%3ggbf1a6d0bf6e359db3j5h089c718e9sd  , and then, your specific code is %3ggbf1a6d0bf6e359db3j5h089c718e9sd 
baidu_tongji: 

google_analytics:
rss:

social_comment:
	plat: 1
	duoshuo_shortname:  
	disqus_shortname: lisdev