menu:
	Home: /
	About: /about
	Archive: /archives

ext_link:
	twitter:  
	github:  
	rss:  

blogroll:
	Leigh: http://zhuli.me


widgets: 
- blogroll

excerpt_link: Read More

twitter:
	username:
	show_replies: false
	tweet_count: 5

bdlike:
	enable: true
	type: large
	uid: 
	color: blue
	share: yes

fancybox: true

google_analytics:
rss:

social_comment:
	plat: 1
	duoshuo_shortname:  
	disqus_shortname: lisdev